defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:latest

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: "[ -d node_modules ] || npm ci"
      - save_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm t -- --i
          environment:
            NODE_OPTIONS: --max-old-space-size=1536
            JEST_JUNIT_OUTPUT_DIR: junit
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
workflows:
  version: 2
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
